Back to simple check

diff --git a/.github/workflows/large-file-check.yaml b/.github/workflows/large-file-check.yaml
--- a/.github/workflows/large-file-check.yaml
+++ b/.github/workflows/large-file-check.yaml
@@ -19,21 +19,12 @@ jobs:
           # Iterate through all commits in the branch
           for commit in $(git log --pretty=format:'%H' origin/master..HEAD); do
             # Check all files in the commit
-            for file in $(git diff-tree --no-commit-id --name-only -r $commit); do
-              # Check if the file has been introduced in this branch, or existed on master
-              if git diff --name-only $(git merge-base HEAD master) HEAD | grep $file; then
-                # If we cannot `git show` a file, its not in commit's tree and we need to
-                # show it in the previous commit
-                if git show $commit:$file 2>&1 | grep -q -E "fatal: path '.+' does not exist in '\w+'"; then
-                  file_size=$(git show $commit~1:$file | wc -c)
-                else
-                  file_size=$(git show $commit:$file | wc -c)
-                fi
-                # Check if file size is larger than 100kb
-                if [ $file_size -gt 100000 ]; then
-                  echo "Error: File $file in commit $commit is larger than 100kb"
-                  exit 1
-                fi
+            for file in $(git diff-tree --diff-filter=d --no-commit-id --name-only -r $commit); do
+              file_size=$(git show $commit:$file | wc -c)
+              # Check if file size is larger than 100kb
+              if [ $file_size -gt 100000 ]; then
+                echo "Error: File $file in commit $commit is larger than 100kb"
+                exit 1
               fi
             done
           done
